---
- name: Restart apache webserver and change the configuration.
  hosts: webserver
  tasks:
    - name: Change the permission in httpd.conf
      replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: "AllowOverride None"
       replace: "AllowOverride AuthConfig"
       mode: 0644
      notify:
       - restart httpd

    - name: Enable the serive
      service:
       name: httpd
       enabled: yes
      notify:
       - restart httpd

  handlers:
    - name : restart httpd
      service:
       name: httpd
       state: restarted
...